version: '3.7'

services:
  app:
    build:
      context: .
    tty: true
    environment:
      - REACT_APP_API_TOKEN=${REACT_APP_API_TOKEN}
    volumes:
      - /app/node_modules
      - .:/usr/src/client:rw,cached
    ports:
      - "80:3000"
